name: PHPCS Code Review for WordPress Coding Standards

on: [push, pull_request]

jobs:
  phpcs:
    name: PHPCS
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3.5.3

      # Set up PHP environment
      - name: Set up PHP
        uses: shivammathur/setup-php@2.25.5
        with:
          php-version: '8.2'
          tools: composer

      # Install the necessary dependencies
      - name: Install dependencies
        run: |
          composer require --working-dir=./src --dev squizlabs/php_codesniffer
          composer require --working-dir=./src --dev wp-coding-standards/wpcs

      # Set the coding standards for PHPCS
      - name: Set PHPCS standards
        run: ./src/vendor/bin/phpcs --config-set installed_paths ./src/vendor/wp-coding-standards/wpcs

      # Run PHPCS with the WordPress coding standards on the specified files and directories
      - name: Run PHPCS
        run: ./src/vendor/bin/phpcs --standard=WordPress --extensions=php ./src/src/* ./src/resources/* ./src/index.php ./src/plugin-name.php
