name: PHPCS Code Review

on: [push, pull_request]

jobs:
  phpcs:
    name: PHPCS
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.3

      - name: Set up PHP
        uses: shivammathur/setup-php@2.25.5
        with:
          php-version: '8.2'
          tools: composer

      - name: Allow PHPCSUtils dependencies
        run: composer config --global allow-plugins.dealerdirect/phpcodesniffer-composer-installer true

      - name: Install dependencies
        run: |
          composer require --working-dir=.. --dev squizlabs/php_codesniffer
          composer require --working-dir=.. --dev phpcsstandards/phpcsutils
          composer require --working-dir=.. --dev wp-coding-standards/wpcs

      - name: List project directory contents
        run: ls -al ..

      - name: List vendor/bin contents
        run: ls -al ../vendor/bin/

      - name: Print working directory
        run: pwd

      - name: Set PHPCS standards
        run: ../vendor/bin/phpcs --config-set installed_paths ../vendor/wp-coding-standards/wpcs

      - name: Run PHPCS
        run: ../vendor/bin/phpcs --standard=WordPress --extensions=php src/* resources/* index.php plugin-name.php
