name: WordPress Coding Standards

on:
  push:
    branches:
      - develop

jobs:
  wpcs:
    name: WPCS Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@2.26.0
        with:
          php-version: '8.2.11'
          tools: composer, cs2pr

      - name: Install dependencies
        run: composer install --working-dir=./src

      - name: Setup WordPress Coding Standards
        run: |
          cd ./src
          composer create-project wp-coding-standards/wpcs --no-dev

      - name: Run WPCS
        run: |
          cd ./src
          vendor/bin/phpcs --standard=WordPress ./resources ./src ./index.php ./plugin-name.php --report=checkstyle | cs2pr
